import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "next-themes";
import NavBar from "@/components/NavBar";
import { Toaster } from "react-hot-toast";
import SyncUserClient from "@/components/SyncUserClient"; 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Їжборщ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="uk" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
            <SyncUserClient />

            <div className="min-h-screen">
              <NavBar />
              <main className="py-8">
                <div
                  className="flex justify-center"
                  style={{
                    paddingLeft: "300px",
                    paddingRight: "325px",
                  }}
                >
                  <div className="w-full max-w-[1200px]">{children}</div>
                </div>
              </main>
            </div>

            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
